#! /bin/sh
##################################################################

# dbpurge by Jeff Johnston <jj358mhz@gmail.com>
# Allows schedule purge (delete) from your Dropbox app
# THIS FILE: /usr/local/bin/dbpurge
# No Warranty is implied, promised or permitted.

# File Locations for Raspberry Pi (Debian based)

# /usr/local/bin/dbpurge       	    (this file)
# /etc/dbpurge/dbpurge.conf     (configuration file)

# Add the following line to root's crontab (via sudo crontab -e):
#       xx * * * *   [ -x /usr/local/bin/dbpurge ] && /usr/local/bin/dbpurge cron > /dev/null
# This will purge an archive xx minutes after the top of every hour. You can update to suit your needs.

# Create these Folders if they don't exist:
# /etc/dbpurge

###############################################################
# REQUIRES (from /etc/dbpurge/dbpurge.conf):
#   ARCHIVE_FOLDER
###################  >>> ENJOY !    ################################

# PATH added in case it is not set when cron runs @reboot
PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:

# Make config changes to the following file...
CONFIGFILE=/etc/dbpurge/dbpurge.conf

#  In normal usage no changes should be made below...
UNIXTIME=`date +%s`
TIMESTAMP=`date +%F-%a-%H%M`

# Check and load the conf file
[ -f "$CONFIGFILE" ] && . $CONFIGFILE

# Dropbox purge

DBFILE_PURGE=$(ls -tr $ARCHIVE_FOLDER | head -1)

sudo -u pi $DBSCRIPT delete "$DBFILE_PURGE"

exit 0
