#!/bin/bash -v

set -x

##################################################################

#  radioplay by MattRock <matt@mattrock.net>
#  Modified by <glyman3@gmail.com> to do local save only, auto-purge files
#  and optionally save copy of audio with dead air removed and sped up
#  No Warranty is implied, promised or permitted.

# Note: radioplay needs to be run as root since Darkice needs to run as root.

# REQUIRED
## Create these Folders if they don't exist:
## /etc/radioplay
## /var/lib/radioplay
## /path/to/your/ARCHIVE_FOLDER

#  Note that if system is rebooted then the next file save will only include from the time of
#  reboot (or system start) to the top of the hour (or time cron last ran).

#  File Locations for Raspberry Pi (Debian based)
### /usr/local/bin/radioplay          ( this file)
### /etc/radioplay/radioplay.conf     ( configuration file )
### /etc/darkice.cfg                  ( darkice config )

#  Add the following line to root's crontab (via sudo crontab -e):
#       00 * * * *   [ -x /usr/local/bin/radioplay ] && /usr/local/bin/radioplay cron > /dev/null
#       This will create an archive every hour on the hour.
#  Another cron alternative is to create a radioplay file and place it in /etc/cron.d/ containing the
#  cron line as shown above.

# Example of job definition:
# .---------------- minute (0 - 59)
# |  .------------- hour (0 - 23)
# |  |  .---------- day of month (1 - 31)
# |  |  |  .------- month (1 - 12) OR jan,feb,mar,apr ...
# |  |  |  |  .---- day of week (0 - 6) (Sunday=0 or 7) OR sun,mon,tue,wed,thu,fri,sat
# |  |  |  |  |
# *  *  *  *  * user-name  command to be executed

##################################################################

# PATH added in case it is not set when cron runs @reboot
PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:

# Make config changes to the following file...
CONFIGFILE=/etc/radioplay/radioplay.conf

#  In normal usage no changes should be made below...
PID=$(systemctl show -p MainPID darkice.service 2>/dev/null | cut -d= -f2)
LIBDIR=/var/lib/radioplay
RPINDEX=$(cat /var/lib/radioplay/radioplay.index)
TIMESTAMP=$(date +%F-%a-%H%M)
ARCHIVE_FOLDER_SIZE=$(df -H "$ARCHIVE_FOLDER" | sed '1d' | awk '{print $5}' | cut -d'%' -f1)
PURGABLE_FILES=$(ls -tr "$ARCHIVE_FOLDER"/*.mp3 | head -n 1)

# Check and load the conf file
[ -f "$CONFIGFILE" ] && . $CONFIGFILE

# Don't allow disk use above 90% regardless of what is in conf file...
#  if you use separate partitions then you might be able to use more than 90
if [ "$DISK_CAP" -gt "90" ];then
	DISK_CAP=90;
fi

# Check for a prep command
case "$1" in
	init)
	printf "Initializing radioplay \n"
	echo "$TIMESTAMP" > $LIBDIR/radioplay.index
	[ -f /tmp/radioplay_active.mp3 ] && sudo chmod 644 /tmp/radioplay_active.mp3
	;;

	cron)
	echo "$LIBDIR/$RPINDEX.mp3" > /tmp/darkice.file-0."$PID"
	kill -s 10 "$PID"
	echo "$TIMESTAMP" > $LIBDIR/radioplay.index
	sleep 5
	/usr/bin/id3v2 --artist "$ID3V2ARTIST" --album "$ID3V2ALBUM" --song "$ID3V2SONG" --year "$ID3V2YEAR" --comment "$ID3V2DESC" $LIBDIR/"$RPINDEX.mp3"

	 # save full recording
	if [[ "$SAVETYPE" = "all" || "$SAVETYPE" = "full" ]];then
		cp "$LIBDIR/$RPINDEX.mp3" "$ARCHIVE_FOLDER/"
		chmod 644 "$ARCHIVE_FOLDER/$RPINDEX.mp3"
		chown "$ARCHIVE_FOLDER_OWNER:$ARCHIVE_FOLDER_OWNER" "$ARCHIVE_FOLDER/$RPINDEX.mp3"
	fi

	# save trimmed recording
	if [[ "$SAVETYPE" = "all" || "$SAVETYPE" = "trim" ]];then
		sox "$LIBDIR/$RPINDEX.mp3" "$ARCHIVE_FOLDER/$RPINDEX""_""$SHORT_LOCATION""_trimmed.mp3" silence -l 1 0.1 "$THSHOLD" -1 1.0 "$THSHOLD" tempo "$TEMPO"
		chmod 644 "$ARCHIVE_FOLDER/$RPINDEX""_""$SHORT_LOCATION""_trimmed.mp3"
		chown "$ARCHIVE_FOLDER_OWNER:$ARCHIVE_FOLDER_OWNER" "$ARCHIVE_FOLDER/$RPINDEX""_""$SHORT_LOCATION""_trimmed.mp3"
	fi

	rm $LIBDIR/"$RPINDEX.mp3" && rm /tmp/darkice.file-0."$PID" # cleanup

	# First, purge recording files that are older than our max age for them...
	find "$ARCHIVE_FOLDER" -iname '*.mp3' -mmin +"$ARCHIVE_AGE" -print0 | xargs -0 --no-run-if-empty  /bin/rm

	# Next, delete some more if we need the disk space AND there are some to delete...
	while  [ $DISK_CAP -lt "$ARCHIVE_FOLDER_SIZE" ] && [ "$(find "$ARCHIVE_FOLDER" -maxdepth 1 -name '*.mp3' -print -quit)" ]
	do
		rm "$PURGABLE_FILES"
	done

	# Cleanup
	[ -f /tmp/radioplay_active.mp3 ] && sudo chmod 644 /tmp/radioplay_active.mp3 # allow copying of active recording
	;;

	*)
	echo "Usage: $0 {init|cron}" >&2

	exit 1
	;;
esac

exit 0
