#!/bin/bash
echo "***** RUNNING PRE-INSTALLATION TASKS *****"
case $(basename $(readlink /proc/1/exe)) in
  systemd)
    pgrep -f pi-slack > /dev/null
    if [[ $? -eq 0 ]]; then
        echo "pi-slack appears to be running, stopping the service"
        systemctl stop pi-slack || echo -en ''
        pgrep -f pi-slack > /dev/null
        if [[ $? -eq 0 ]]; then
            echo 'pi-slack service has been stopped'
        fi
    fi
  ;;
  *)
    echo "Init system not found"
    exit 1
  ;;
esac
